import type { Metadata } from 'next'
import { Source_Sans_3 } from 'next/font/google'
import './globals.css'
import Header from './components/Header'

const sourceSans = Source_Sans_3({
  variable: '--font-main',
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={sourceSans.variable}>
      <body className='antialiased flex flex-col items-center mt-10'>
        <Header />
        {children}
      </body>
    </html>
  )
}
